#!/bin/sh
#
# Check whether a magic file is present on disk or not
#
# To use a warning instead of a critical status when file is absent, use -w
#
# Copyleft Gabriel Filion
#
# This plugin is released under the GPL v3+ license. To get a copy of the
# license text visit: https://www.gnu.org/licenses/gpl-3.0.txt
#

NOTIFY_FILE=/var/run/reboot-required

RETURN_CODE=2
RETURN_STATUS=CRITICAL
if [ "$1" = "-w" ]; then
    RETURN_CODE=1
    RETURN_STATUS=WARNING
fi

if [ -f $NOTIFY_FILE ]; then
    echo "$RETURN_STATUS: $(cat $NOTIFY_FILE)"
    exit $RETURN_CODE
fi

echo "OK: reboot not required"
exit 0
